### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by danthony06** [ros2/ros2_tracing#118]
I just tried building Jazzy from source on Fedora 40. I'm getting the following error in tracetools.

`--- stderr: tracetools                                                                                                
In file included from /usr/include/lttng/tracepoint-event.h:69,
                 from /src/ros2_jazzy/build/tracetools/include/tracetools/tp_call.h:514,
                 from /src/ros2_jazzy/src/ros2/ros2_tracing/tracetools/src/tp_call.c:18:
/src/ros2_jazzy/build/tracetools/include/tracetools/tp_call.h: In function ‘lttng_ust__event_probe__ros2___rclcpp_ring_buffer_enqueue’:
/src/ros2_jazzy/build/tracetools/include/tracetools/tp_call.h:480:5: error: initialization of ‘const uint64_t *’ {aka ‘const long unsigned int *’} from ‘uint64_t’ {aka ‘long unsigned int’} makes pointer from integer without a cast [-Wint-conversion]
  480 |     ctf_integer(const uint64_t *, index, index_arg)
      |     ^~~~~~~~~~~
gmake[2]: *** [CMakeFiles/tracetools.dir/build.make:104: CMakeFiles/tracetools.dir/src/tp_call.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:163: CMakeFiles/tracetools.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
gmake: *** [Makefile:146: all] Error 2
`

**Comment by christophebedard** [comment]
Backport done in https://github.com/ros2/ros2_tracing/pull/119, closing this.

**Comment by danthony06** [comment]
Thanks!
