### ISSUE TITLE
Real time data tracing

### ISSUE THREAD

**Issue by hs2041** [ros2/ros2_tracing#13]
Hi, 
Using ros2_tracing, I am able to generate a ust file which provides me with all the trace calls while the system was running. However, is there a way to get these calls while the system is running in real-time?

**Comment by christophebedard** [comment]
Hi! The tracer (LTTng) has features to do this. Take a look at the “live mode” and the “network streaming mode” https://lttng.org/docs/v2.13/#doc-tracing-session-mode. However, note that most of the trace analysis tools related to `ros2_tracing` (namely `tracetools_analysis` and Trace Compass) are not designed to support live analysis, so you might need to adapt them, look for a tool that does that (for example, I think people have worked on integrating trace data into Grafana), or build one yourself using the babeltrace2 library.

**Comment by hs2041** [comment]
Hey, thanks. I'll look into it.
