### ISSUE TITLE
Gracefully handle older versions of LTTng

### ISSUE THREAD

**Issue by christophebedard** [ros2/ros2_tracing#16]
(Issue moved from GitLab, see: https://gitlab.com/ros-tracing/ros2_tracing/-/issues/142)

**Comment by christophebedard** [comment]
@cottsay I ran all tracing tests on RHEL 9 with LTTng 2.12, including some tests I'm adding in #54, and everything passes. Given that LTTng (`liblttng-ust-dev`, `python3-lttng`, `lttng-tools`) is now expected to be installed on Linux, and since the lowest common denominator is version 2.12, which works fine, I don't think we really need to do this anymore.

You said recently that you still wanted this to be improved, though, so I'm just wondering why exactly.

**Comment by cottsay** [comment]
> so I'm just wondering why exactly.

I think that it's a valid effort to support as many Linux distributions as is reasonably possible in packages which are considered part of the core of ROS 2, including ones which have previously been supported like RHEL 8. I'm really not asking for much here. Assign the ticket to me if you're not willing to do it yourself.

**Comment by christophebedard** [comment]
Sorry, that's not what I meant! I'm all for making this kind of improvement.

> including ones which have previously been supported like RHEL 8

Thanks, you answered my question.
