### ISSUE TITLE
Mention needing to start tracing before starting application

### ISSUE THREAD

**Issue by christophebedard** [ros2/ros2_tracing#40]
Otherwise, the events in the [initialization phase](https://github.com/ros2/ros2_tracing/blob/rolling/doc/design_ros_2.md#general-guidelines) aren't recorded, which makes the rest of the trace data unusable. This isn't really obvious to people, e.g.: https://gitlab.com/ros-tracing/tracetools_analysis/-/issues/54#note_1195588968

This warning/note could perhaps go somewhere in this section: https://github.com/ros2/ros2_tracing#tracing

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/seeking-feedback-on-enabling-post-launch-tracing-in-ros2-tracing/44130/1
